version: 1.0.{build}
image:
- Visual Studio 2017

environment:
  matrix:
    - TAG: latest
    - TAG: lts

  DOCKER_USER:
    secure: w2Rmx1xX/Sr8G9FYlbZdiA==
  DOCKER_PASS:
    secure: 1naXTmc0kovqpqIFM7CW9g==

matrix:
  allow_failures:
    - TAG: latest
    - TAG: lts
  fast_finish: true

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1
